image: node:11

cache:
    paths:
    - node_modules/

stages:
   - build
   - downstream

#---------------------------------------------------------------   
     
buildDev:
  stage: build
  only:
    - dev
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
    - dist/PeBLCore.js

#----------------------
      
buildQA:
  stage: build
  only:
    - qa
  script:
    - npm install
    - export MINIMIZE=true && npm run build
  artifacts:
    paths:
    - dist/PeBLCore.js

#----------------------

buildProd:
  stage: build
  only:
    - master
  script:
    - npm install
    - export MINIMIZE=true && npm run build    
  artifacts:
    paths:
    - dist/PeBLCore.js



#---------------------------------------------------------------   


downstreamDev:
  stage: downstream
  trigger:
    project: pebl/WebReader
    branch: Dev
